### PR TITLE
Workaround tommath issue #56, affects random bigint numbers > 32bits

### PR DESCRIPTION
**Pull request by skids**
See rakudo RT#109586

### CODE REVIEW

**Comment by skids** [comment]
Totally untested (up way past bedtime) and needs review.

**Comment by skids** [comment]
Managed to squeeze off a rakudo and nqp test run before bed; they were OK.  Only tested on 64-bit linux.  Needs testing on 32-bit.

**Comment by jnthn** [comment]
I don't have a 32-bit thingy handy to try it out on, but I'm happy enough with the patch otherwise.

**Comment by jnthn** [comment]
Any reports from 32-bit on this?

**Comment by FROGGS** [comment]
The tests pass before and after applying the changes on x86.

**Pull request merged**
