### PR TITLE
Convert the use of a Variable Length Array to a regular allocation

### PR DESCRIPTION
**Pull request by nwc10**
This should restore the build on MSVC.

### CODE REVIEW

**Comment by nwc10** [comment]
@jnthn are my assumptions about the FSA being a better fit reasonable?

I haven't actually benchmarked them :-)

**Comment by nwc10** [comment]
@coke I thought it clearer (for history) to merge my changes to your original commit into one change. It's not clearer for attribution - this is still fine with you?

**Comment by nwc10** [comment]
`alloca` would better.

**Comment by coke** [comment]
@nwc10 - sure. The config change was ok, but my code change was a WIP that needed fixing anyway, thanks!

**Comment by nwc10** [comment]
celo_duro suggested `alloca`. It seems the simplest approach - see #1543

**Pull request closed without merging**
