### PR TITLE
Update OS versions in Azure CI config

### PR DESCRIPTION
**Pull request by MasterDuke17**
Use newest non-preview versions as default and name the older available versions.

### CODE REVIEW

**Review by patrickbkr — APPROVED** [review]
Looking good. Can we have the same change in NQP and rakudo as well to keep them as much in sync as possible?

**Comment by MasterDuke17** [comment]
> Looking good. Can we have the same change in NQP and rakudo as well to keep them as much in sync as possible?

Any idea what's going on with the fails in the new windows jobs?

**Comment by patrickbkr** [comment]
A quick googling tentatively points to a batch error. I don't see anything obviously wrong with the failing command though.

**Comment by MasterDuke17** [comment]
Yeah, I can't find anything definitive. For now I'm just going to back out the windows changes.

**Pull request merged**
