### PR TITLE
Pre-declare loop vars.

### PR DESCRIPTION
**Pull request by 0racle**
Fixes builds on older versions of gcc.

### CODE REVIEW

**Comment by 0racle** [comment]
This is similar to commit fc09255. Just prior to that commit being merged, another commit was merged which added more of these loops var declarations.

Can we have these detected in the CI pipeline to prevent breaking builds on older systems?

**Comment by ugexe** [comment]
fwiw the Rakudo Circle CI has been complaining/failing over this for awhile

**Comment by niner** [comment]
Is there really no other way to convince gcc that this is correct code? We've just got rid of the restrictions imposed on us by MSVC. It would be a shame if we now needed to code like it's 1995 because of gcc versions that really fully support C99 and even parts of C11.

**Comment by patrickbkr** [comment]
I have a PR for a different approach here: [#1318](https://github.com/MoarVM/MoarVM/pull/1318)

**Comment by 0racle** [comment]
I have confirmed that Moar also builds successfully for me if I manually specify `CFLAGS='-std=gnu99'`, so I'm happy for #1318 to be merged in lieu of in this one. It also means we could revert fc09255

**Comment by patrickbkr** [comment]
#1318 has been merged. So I'll close this one.
@0racle Thanks for the report and work you put into this!

**Pull request closed without merging**
