### PR TITLE
fix appveyor.yml

### PR DESCRIPTION
**Pull request by sumanstats**
+ update worker image 2019
+ no need to have separate install for strawberry perl
+ install zstd https://github.com/facebook/zstd, while building
+ fix the correct nqp link https://github.com/Raku/nqp

### CODE REVIEW

**Comment by sumanstats** [comment]
@patrickbkr Building in single CI provider `AzureCI` is good. If possible, it would be better to put three badges in `README.md` each for separate platform `Linux`, `Windows`, and `MacOS`. So that one would know easily in which `OS` testing is failing.

**Comment by sumanstats** [comment]
A glimpse of badges helps to know in which `OS` the test is failing. 

Its better to have three badges but we can adjust 9 badges. Some repos have such badges (*just an example*):
Capture

**Comment by patrickbkr** [comment]
It seems Microsoft just broke their status badge links. This makes it difficult to test. Hope they fix this soon.

Also I didn't manage to retrieve a status badge for a matrix job. I only managed to retrieve the status of the meta job: <https://dev.azure.com/Rakudo/rakudo/_apis/build/status/rakudo.rakudo?branchName=master&stageName=Test&jobName=T>

[This MSDN page](https://docs.microsoft.com/en-us/rest/api/azure/devops/build/status/get?view=azure-devops-rest-5.1) gives some hints on how to put such URLs together.

**Comment by patrickbkr** [comment]
As announced in the first comment, all CI toolchains apart from Azure have been disabled. I'll thus close this PR. Thanks for initially looking into this!

**Pull request closed without merging**
