### PR TITLE
Add getppid op

### PR DESCRIPTION
**Pull request by ugexe**
Allows a child process to get the parent process id, and thus guess if it has become orphaned.

### CODE REVIEW

**Comment by ugexe** [comment]
Hold off on this until then next libuv point release. It seems libuv 1.16.0 broke builds on many windows configurations. [PR](https://github.com/libuv/libuv/pull/1623) has been submitted.

**Comment by ugexe** [comment]
libuv 1.16.1 fixed the windows issue noted previously and getppid works.

@jnthn 
Using any libuv past v1.14.1, however, results in an [unrelated proc regression on windows](https://github.com/libuv/libuv/issues/1625) that was not noticed before. This means https://github.com/MoarVM/MoarVM/commit/8b53b1ebbdef93e69f07c9c3fd1e367f3376c4f9 will need to be reverted if there is no solution before the next MoarVM release.

**Comment by AlexDaniel** [comment]
Why did you close this?

**Comment by ugexe** [comment]
I was tired of being mentioned in an individuals commit messages in the perl6 community, and when I spoke up about it someone belittled it and encouraged the perpetrator that they were doing the right thing despite having no background information on what happened. I don’t want to feel like I’m being gaslighted in the community I’ve been a part of for 5 years, yet in the last few months I always know exactly who will send a patronizing smiley face as their response if someone speaks up about anything they don’t personally believe. So I’ve chosen to speak up with my work/merit by closing my PRs until/if this recent change in attitude goes away.

**Comment by zoffixznet** [comment]
> when I spoke up about it

Personally, what I saw is you calling another community member an angry racist, publicly, in a channel of 300 people. Which seemed to stem from an unfortunate choice of a test input string. The user both repeatedly apologized and offered to follow up on the matter in private. 

I looked through the user's repos and found just a single commit mentioning you and all it said is you refused to support a feature.

> So I’ve chosen to speak up with my work/merit by closing my PRs until/if this recent change in attitude goes away.

Judging by comments on your closures, everyone's simply confused and no one knows wtf you're talking about. "patronizing smiley face"? wat? Nothing's gonna change if no one knows what needs to change.

**Comment by AlexDaniel** [comment]
> "patronizing smiley face"? wat?

I think it's about my message. See this: https://irclog.perlgeek.de/perl6/2017-11-23#i_15486717

I've sent it because I disapprove continuous bullying for making a mistake. As for the commit messages, I've spent an unjustified amount of time trying to find them, and I didn't. Maybe they were force-pushed into nonexistence, I don't know. There was a commit saying that something is done “just to please zef” but that looked rather technical to me.

The smiley face could've been replaced with words, something like “I think he understood everything, please stop”. It could be that my position is wrong. If so, let me know.

**Comment by AlexDaniel** [comment]
Ah, maybe it's also worth elaborating a little bit on this:

> despite having no background information on what happened

When I see public bashing of someone who is clearly not being aggressive at the moment of bashing, I want it to stop. You are right that I didn't have enough information (and still don't have it), but I believe that we can have peaceful discussions of these issues.

**Comment by ugexe** [comment]
> ugexe:   title (tyil) that exception from ComUnit::Repository but you seem so busy writing pissed off comments about zef in all your module commit messages that I can see why you would not have had the time to just look at the source

> tyil:    I wonder why

> ugexe:   Me too

> tyil: 	I don't really feel like having to go through this again

> tyil:    feel free to pm w/ otr if you truly wonder ;)

if we want to ignore the above we can pretend i'm just making all of this up.

**Comment by zoffixznet** [comment]
> if we want to ignore the above we can pretend i'm just making all of this up.

I'm unsure what we're meant to be paying attention to there. You're publicly accusing tyil of `"writing pissed off comments about zef in all your module commit messages"`, an action for which two people so far failed to find any evidence of.

I've no idea what `"w/ otr"` means, but the rest of the conversation suggests to me some discussion happened between you two in the past—a discussion I, and likely most of the other people you're blackmailing, don't even know about.

So from where I'm sitting: I see you're pissed off at single guy, for reasons I don't know and which you're being very cryptic about. The other day, I got a couple dozen notifications about closed PRs and Issues from you. And today you said those were because we need an attitude adjustment and I've no idea what that even means.

I don't intend to follow this conversation after this comment, and I'll end it with something that was said on IRC awhile back:

> sorry, we don't play the nuclear blackmail game here

**Comment by AlexDaniel** [comment]
> I've no idea what "w/ otr" means

I was wondering that too. My best guess is that “otr” itself stands for “off-the-record”, so the person was simply implying that it'd be a private conversation not recorded anywhere. The wording is really weird but that's all I could make out of it.

> yet in the last few months I always know exactly who will send a patronizing smiley face as their response if someone speaks up about anything they don’t personally believe

If I am the problem, we should discuss it. Sometimes I'm indeed too vocal about some things, so given enough feedback we can all become better I think.

**Comment by jnthn** [comment]
I'm sad to see all of this.

First of all, I'd hope that as a community we can agree the language used in tyil's now-deleted upload to CPAN is unacceptable, and falls well below what we should expect of those who consider themselves part of our community. In my view, it's quite right that tyil was publicly challenged about this, because we should not be seen as a community that is accepting of such behavior. At the same time, people can make mistakes that are out of character, and I believe tyil deserves the opportunity to demonstrate that's all it was, without being reminded of it every single day.

Secondly, if ugexe says he has been repeatedly mentioned in commits - I'm assuming in a way that he finds hurtful or that makes him lose his wish to continue being part of the community - then I'd like to see that received in a more accepting and caring manner than I see in this thread, where the first instinct seems to have been to request proof, then claim this is some kind of "nuclear blackmail". To which I can only say - uh, really? Is it really more likely that somebody who has contributed in a huge number of ways to our community over the years suddenly decides to engage in some strange blackmail plot, than that they legitimately *were* hurt by something that happened?

Further, trying to argue that something is "rather technical" isn't particularly helpful. It doesn't matter if *you* wouldn't be upset by it, or if - as may well be the case - the author didn't intend to cause hurt to another person and was just ranting about some inanimate bit of software, forgetting that there's real people on the other side of that software. The point is that somebody in our community is quite evidently feeling crap, and I think it would have been nice if the reactions here involved a good dose more empathy.

@ugexe, if you wish to discuss this further privately, feel free to drop me an email or catch me on IRC (OK, not *right* now as I should already be sleeping...) Ditto for the others of you on this thread.

**Comment by 2colours** [comment]
Well, this didn't age too well.

**Pull request closed without merging**
