### PR TITLE
Close socket on async error during an async connection

### PR DESCRIPTION
**Pull request by Kaiepi**
Related to https://github.com/rakudo/rakudo/issues/4370.

### CODE REVIEW

**Comment by Zer0-Tolerance** [comment]
Hi , any idea when this will be merged ?

**Comment by Zer0-Tolerance** [comment]
Hi ,
Raku is still having issue when closing connection after timeout on OSX in version 2021.07, any idea how this can be fixed ?

**Comment by Kaiepi** [comment]
@Zer0-Tolerance Asynchronous connections don't close on timeout on master, but do with these changes, but again, I'm testing on OpenBSD, and I don't have an OS X system to test with offhand.

**Comment by Kaiepi** [comment]
The golf for this is similar to [before](https://github.com/rakudo/rakudo/pull/4391#issuecomment-895145873):

```raku
use v6;
shell "ktrace dump ktrace.out -p $*PID";
say try { await IO::Socket::Async.connect: '127.0.0.1', 12345 } // $!;
sleep;
```

But the process for producing a dump and viewing it with the more BSD-ish flavour of `ktrace`:

```sh
$ ktrace -p $*PID
$ kdump | less
```

Looks to be equivalent to this on [newer versions of OS X](https://www.unix.com/man-page/mojave/1/ktrace/):

```sh
$ ktrace dump ktrace.out -p $*PID
$ ktrace trace -R ktrace.out | less
```

**Comment by niner** [comment]
Thanks for the fix! And sorry for the long delay.

**Pull request merged**
