### PR TITLE
Update libuv to 1.26

### PR DESCRIPTION
**Pull request by ugexe**

### CODE REVIEW

**Comment by ugexe** [comment]
Notables:

* src,include: define UV_MAXHOSTNAMESIZE
* thread: allow specifying stack size for new thread
* unix,win: add uv_os_uname()

**Comment by jnthn** [comment]
Will do this after this month's release (or at least, after the release branch is made), so we get more testing time

**Comment by ugexe** [comment]
Closing/opening to rebuild

**Comment by atweiden** [comment]
@ugexe in the future you can also do

```sh
git commit --amend --no-edit
git push -f
```

to force a rebuild without changing anything

i have it aliased to [git touch](https://github.com/atweiden/macfiles/blob/a9d29f2a0132cb70fca73262a556a4318e262aad/.config/git/config#L28)

**Pull request merged**
