### PR TITLE
Switch MVM_coerce_n_s to Ryū from Grisu3 with a sprintf fallback

### PR DESCRIPTION
**Pull request by nwc10**
As Zoffix notes in commit 067c0594103a0254 which switched **to** Grisu3, as Grisu3 can only handle ~99.5% of cases, it needs to be paired with a fallback algorithm for the other 0.5%. To save adding a **second** external library, we had been using sprintf with the format %17g for this. Using %17g instead of the default width of 15 produced *correct* results, in that the output would always round trip correctly, but for some values it was not producing the *optimal* result - ie the shortest decimal representation where two or more to the same binary value.

Unfortunately for some obvious cases, what we had exposed this. For example:

    nqp -e 'nqp::say(1e23)'
    9.9999999999999992e+22
    nqp -e 'nqp::say(1e23 - 9.9999999999999992e+22
    0

As noted in that commit, Dragon4 would have been a better fallback, and at the time "Grisu3+Dragon4 [was] the current state of the art."

Since then Ryū has been published. The author states that it is faster, but I haven't verified these benchmarks. As it is a *complete* algorithm - it handles 100% of inputs - we can use it without needing any fallback, thus simplifying our code and fixing the buggy sub-optimal results.  Hence am not concerned if it isn't always faster than Grisu3, as correctness trumps "getting the wrong answer as fast as possible".

Current state of the art might actually be Dragonbox, but the reference implementation is in C++, and it is not clear whether that algorithm has had sufficient peer review yet to find any subtle problems. If someone else authors a suitably licensed implementation in portable C, we should consider switching to it, but it is not worth doing that ourselves.

### CODE REVIEW

**Comment by nwc10** [comment]
@jnthn Is it OK to add this repository as a 3rdparty repository? The code we need is under an Apache2 license.

Also, did I do it correctly? The don't see to actually have proper tags or releases, so to ensure reproducable I guess we need to go for a particular commit, rather than `master`, as we don't want what we get to move underneath us.

Draft PR for now so we get to see what the CI makes of it. I think that the code is sufficiently portable, but let's check...

**Comment by nwc10** [comment]
Pushed an update (that I failed to do earlier) - fixes one significant comment goof (should be *exponent* not *mantissa*) and one thinko in a commit message (missed an *I*) but I'm sure that I spotted a second commit message goof, and I can't find it now.

Also I don't get some of what codefactor is complaining about - it's reporting new issues in `MVM_radix` and `MVM_coerce_istrue` and I didn't change those. I think it's fair to be annoyed with `MVM_coerce_n_s` but I don't think that there is any way to make that **actually** simpler, compared with "shuffled around a bit to appease the tool, but now not as linear for the human to read".

**Comment by nwc10** [comment]
```representation where two or more to the same binary value.```

found the other missing word again - *map*

**Comment by nwc10** [comment]
Fixed that commit message. I believe that there are no more to find.

**Comment by patrickbkr** [comment]
We are now shortly after the release. Best time to merge of the month!

**Comment by jnthn** [comment]
> @jnthn Is it OK to add this repository as a 3rdparty repository? The code we need is under an Apache2 license.

Yes

> Also, did I do it correctly? The don't see to actually have proper tags or releases, so to ensure reproducable I guess we need to go for a particular commit, rather than master, as we don't want what we get to move underneath us.

We've tended to fork such things under the `MoarVM` organization and use that.

**Comment by nwc10** [comment]
> We've tended to fork such things under the `MoarVM` organization and use that.

That would also solve the problem of "tagging" the version we need, as it would be **our** branch we pull from, and we can update that from upstream when needed. However, **I** don't have permission to fork to MoarVM (just Raku!) so I can't do this.

**Comment by jnthn** [comment]
@nwc10 Forked as https://github.com/MoarVM/ryu (and added @MoarVM/team-moarvm so you have access).

**Comment by nwc10** [comment]
Rebased onto master (else every CI would fail because the tag is so *last month*)

Added 1 commit to change the submodule to https://github.com/MoarVM/ryu

Other than CodeFactor, this should all work...

**Comment by nwc10** [comment]
https://dev.azure.com/MoarVM/6b7ef196-3f6c-40c1-93b8-6350dcf162b2/_apis/build/builds/508/logs/160

```2021-04-30T05:55:53.6122187Z ##[section]Starting: Install libzstd-dev and valgrind
2021-04-30T05:55:53.6386853Z ==============================================================================
2021-04-30T05:55:53.6387769Z Task         : Command line
2021-04-30T05:55:53.6388580Z Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
2021-04-30T05:55:53.6388929Z Version      : 2.182.0
2021-04-30T05:55:53.6389449Z Author       : Microsoft Corporation
2021-04-30T05:55:53.6390716Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
2021-04-30T05:55:53.6391117Z ==============================================================================
2021-04-30T05:55:54.2014528Z Generating script.
2021-04-30T05:55:54.2016329Z Script contents:
2021-04-30T05:55:54.2016922Z sudo apt-get install libzstd-dev valgrind
2021-04-30T05:55:54.2017532Z ========================== Starting Command Output ===========================
2021-04-30T05:55:54.2024964Z [command]/bin/bash --noprofile --norc /home/vsts/work/_temp/1fc57368-e8fb-434f-88bb-cb4ecd432c1f.sh
2021-04-30T05:55:57.7010975Z Reading package lists...
2021-04-30T05:55:57.9548403Z Building dependency tree...
2021-04-30T05:55:57.9595593Z Reading state information...
2021-04-30T05:55:58.1264289Z The following additional packages will be installed:
2021-04-30T05:55:58.1265375Z   gdb gdbserver libbabeltrace1 libc6-dbg libipt1 libzstd1
2021-04-30T05:55:58.1265759Z Suggested packages:
2021-04-30T05:55:58.1272710Z   gdb-doc valgrind-dbg valgrind-mpi kcachegrind alleyoop valkyrie
2021-04-30T05:55:58.1743836Z The following NEW packages will be installed:
2021-04-30T05:55:58.1746677Z   gdb gdbserver libbabeltrace1 libc6-dbg libipt1 libzstd-dev valgrind
2021-04-30T05:55:58.1752446Z The following packages will be upgraded:
2021-04-30T05:55:58.1754080Z   libzstd1
2021-04-30T05:55:58.2101012Z 1 upgraded, 7 newly installed, 0 to remove and 13 not upgraded.
2021-04-30T05:55:58.2101609Z Need to get 23.7 MB of archives.
2021-04-30T05:55:58.2102766Z After this operation, 127 MB of additional disk space will be used.
2021-04-30T05:55:58.2104201Z Get:1 http://azure.archive.ubuntu.com/ubuntu bionic/main amd64 libbabeltrace1 amd64 1.5.5-1 [154 kB]
2021-04-30T05:55:58.2212897Z Get:2 http://azure.archive.ubuntu.com/ubuntu bionic/universe amd64 libipt1 amd64 1.5-1ubuntu1 [28.6 kB]
2021-04-30T05:55:58.2219463Z Get:3 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 libc6-dbg amd64 2.27-3ubuntu1.4 [5163 kB]
2021-04-30T05:55:58.2277766Z Get:4 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 libzstd1 amd64 1.4.8+dfsg-2+ubuntu18.04.1+deb.sury.org+4 [330 kB]
2021-04-30T05:55:58.2886377Z Err:5 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu bionic/main amd64 gdb amd64 8.2-0ubuntu1~18.04
2021-04-30T05:55:58.2888953Z   404  Not Found [IP: 91.189.95.85 80]
2021-04-30T05:55:58.3108780Z Err:6 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu bionic/main amd64 gdbserver amd64 8.2-0ubuntu1~18.04
2021-04-30T05:55:58.3112194Z   404  Not Found [IP: 91.189.95.85 80]
2021-04-30T05:55:58.3344135Z Get:7 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 libzstd-dev amd64 1.4.8+dfsg-2+ubuntu18.04.1+deb.sury.org+4 [411 kB]
2021-04-30T05:55:58.3363984Z Get:8 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 valgrind amd64 1:3.13.0-2ubuntu2.3 [14.3 MB]
2021-04-30T05:55:58.6672678Z Fetched 20.3 MB in 0s (45.1 MB/s)
2021-04-30T05:55:58.6701728Z E: Failed to fetch http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu/pool/main/g/gdb/gdb_8.2-0ubuntu1~18.04_amd64.deb  404  Not Found [IP: 91.189.95.85 80]
2021-04-30T05:55:58.6704884Z E: Failed to fetch http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu/pool/main/g/gdb/gdbserver_8.2-0ubuntu1~18.04_amd64.deb  404  Not Found [IP: 91.189.95.85 80]
2021-04-30T05:55:58.6706982Z E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
2021-04-30T05:55:58.6775588Z ##[error]Bash exited with code '100'.
2021-04-30T05:55:58.6886643Z ##[section]Finishing: Install libzstd-dev and valgrind
```

Clearly it hates me. This is what failed. (Twice.)

**Comment by nwc10** [comment]
And rebased again so that it runs with the fixes from #1484

**Comment by nwc10** [comment]
Rebased onto master, which removes the commit `Convert MVM_num_isnanorinf and MVM_num_{posinf,neginf,nan} to static inline`, which is already on master.

It turns out that I wrote that commit twice, on two different branches, 3 months apart. I figured therefore that it's a good idea to put it into master **before** I attempt to write it a third time.

**Comment by MasterDuke17** [comment]
I just did a local checkout, rebase onto master, rebuilt NQP+Rakudo, and all tests pass, so merging now.

**Pull request merged**
