### PR TITLE
Refactoring conditional directives.

### PR DESCRIPTION
**Pull request by wmarquesr**
A suggestion to compile entire statements and expressions, as suggested by code style guidelines from the Linux Kernel and practitioners.

* [Linux kernel coding style](https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/Documentation/CodingStyle#n892)
* [Living in the #ifdef Hell](https://www.cqse.eu/en/blog/living-in-the-ifdef-hell/)

It might improve code understanding, maintainability and error-proneness.

### CODE REVIEW

**Comment by zhuomingliang** [comment]
Build failed.

**Comment by wmarquesr** [comment]
But the code is note wrong.

**Comment by zhuomingliang** [comment]
Since it doesn't pass travis-ci, I'm closing it. Please feel free to push a new one that passes travis-ci, thanks.

**Comment by jnthn** [comment]
For me variables and the state they introduce, which needs to be understood
to understand the code in question, are a bigger maintenance issue. This
patch introduces a variable at the top level function scope, when it seems
it could have been more narrowly scoped. So I'm not especially convinced
the patch - even if it had compiled on the build server - was an overall
improvement.

**Comment by wmarquesr** [comment]
@jnthn I do not understand whether you agree or not with the patch, if so, should I submit again and pass the tests, would be accepted?

**Pull request closed without merging**
